name: unit tests and pylint, athena submodule module

on: [push]

jobs:
  unit-tests-and-pylint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install tox
        run: pip install tox

      - name: Run tox (tests + pylint)
        run: tox -c ./modules/athena/functions/tox.ini
