name: unit tests and pylint

on: [push]

jobs:
  unit-tests-and-pylint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install tox
        run: pip install tox

      - name: Run tox (tests + pylint)
        run: tox -c ./functions/tox.ini
