name: terraform fmt

on: [push]

jobs:
  terraform-fmt:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - id: fmt
        run: terraform fmt --recursive --check
